### ISSUE TITLE
Wrong month for WandaVision S01E04

### ISSUE THREAD

**Issue by oscarmarcelo** [dispossible/MCU-Timeline#10]
There's a typo in the release date for WandaVision. It should be **February** 5th 2021, not **January**. 🙂 

https://github.com/dispossible/MCU-Timeline/blob/4bfd3f9c140348f278d9ecaa22de36a943f928f1/src/js/data.json#L803

**Comment by dispossible** [comment]
Thanks for flagging that, good spot. I've just pushed the fix.
