### ISSUE TITLE
Agents of S.H.I.E.L.D. - Slingshot is missing

### ISSUE THREAD

**Issue by Slingshot123** [dispossible/MCU-Timeline#11]
Hey, love your website. Just one thing I noticed. The mini-webseries AoS - Slingshot isnt in your list. Take care :)

**Comment by dispossible** [comment]
Hi, glad you like the site! Thanks for letting me know about Slingshot, I'll get it added in.

**Comment by dispossible** [comment]
Slingshot has now been added. I have also added the other digitally released series WHiH. I may need to add a new entry type to separate those out, but for now both are added as TV shows.
