### ISSUE TITLE
Runaways release date

### ISSUE THREAD

**Issue by Slingshot123** [dispossible/MCU-Timeline#12]
hey :) Its me again :D Thanks for including the web series, really love the artwork of your website and I show it to anyone that wants to watch the mcu. I found another little mistake. Runaways Episode 9 & 10 are scheduled in the year 2017, when its actually 2018, so its wrong in the chronicle order.

Have a nice weekend bro

**Comment by dispossible** [comment]
Hi again. Great spot, the old copy and paste catching me out there. Fixed, thanks!
