### ISSUE TITLE
What are you hosting this on?

### ISSUE THREAD

**Issue by MrRubberDucky99** [dispossible/MCU-Timeline#16]
Hi, I am working on the possibility of getting the cards to link to the Disney + for the movies and I was wondering what yours hosting this on so that I know what to use for testing. Thanks!

**Comment by dispossible** [comment]
Hey, 

To answer your question directly it is currently hosted on AWSs Amplify platform, but that shouldn't matter during development as you can run the `npm start` command to run it locally and see it running in browser exactly as you should expect to see it when deployed. There is nothing fancy happening on the server side, it's a static files host.

I have considered adding links to the cards to places to watch the shows, but I have held off thus far for a few reasons: 
* I have been concerned that it could prove very hard to find a link for every show and having only some of them linked up could be annoying. I don't like the inconsistency.
* There may be a whole bunch of shows with regional variations in where they are streamable from. I know for instance the Spiderman films are a pain to get a hold of in the UK (where I am) and are on different services in the US. To name just 2 regions.
* It adds an extra maintenance burden if any of the links get broken over time, which isn't easy to test for if they are only broken in other regions.

I'm happy to look at your solution if you do implement links, but those are your hurdles to overcome :)

**Comment by MrRubberDucky99** [comment]
I have created a pull request with my implementation of the feature
