### ISSUE TITLE
Ms. Marvel tv show is missing from future lineup

### ISSUE THREAD

**Issue by devildog125** [dispossible/MCU-Timeline#22]

**Comment by dispossible** [comment]
Hey, thanks for the message, however it has been my general rule to not add things to the timeline until they have a actual date. It is currently only known that Ms. Marvel will be later this year, making it hard to place. 

I currently have no support in the codebase for vague dates. I will of course add it as soon as it has a scheduled date.

**Comment by raabfelix** [comment]
Hey @dispossible , Ms. Marvel has an release date now. Can you add it?

**Comment by dispossible** [comment]
Hey @raabfelix, thanks for the nudge. I have added Ms. Marvel in. Still no episode names but that's standard of the Disney+ shows not announcing them until release day.
