### ISSUE TITLE
Hawkeye is missing from lineup and is listed to come out Nov. 24th

### ISSUE THREAD

**Issue by devildog125** [dispossible/MCU-Timeline#23]

**Comment by dispossible** [comment]
Thanks for letting me know. I hadn't checked in on the release dates for a few weeks. I'll get that updated now and updated in the next couple hours,  as it appears to have been assigned a release date just over a week ago.

As I eluded to in my last message I generally avoid being too proactive in updating the 'future' timeline entries. I see the use case for this timeline as a tool to assist in (re)watching the released content, and not so much as a news source to keep people up to date on upcoming releases far into the future. There are other places that have people dedicating their time to keeping abreast of the news and press releases, which I just don't have the time to maintain personally.
