### ISSUE TITLE
Far From Home wrongly placed

### ISSUE THREAD

**Issue by rubentavares** [dispossible/MCU-Timeline#29]
Far From Home took place 1 year after Endgame. WandaVision, Loki & Falcon are before that.

**Comment by dispossible** [comment]
Hey,

I had initially placed Far From Home in it's release order, as that seemed to make sense at the time. I have now shifted if to just after the first 3 MCU TV shows, as you are correct that does seem to make sense with the context of the film some time has passed, where the shows lead directly on from Endgame.
