### ISSUE TITLE
Team Thor & Team Darryl

### ISSUE THREAD

**Issue by m010ch** [dispossible/MCU-Timeline#32]
Hello, is there any reason why these one-shots are not included in the timeline?

**Comment by dispossible** [comment]
I'd entirely forgotten about those. I'd dismissed them as semi-cannon DVD extras. A small amount of looking into it seems like Marvel reclassified them as one-shots only at the start of this year when adding them to Disney+. I'll get them added in.

**Comment by DivannKokos** [comment]
Actually they are still out of the canon, even though they available on Disney+, they are classified as non-canon and Darryl later appearing in Thor Love and Thunder, yet it is not the same Darryl. Worth noting that it is not main time line. Its basically a "What If?" by a director, to which you could also add a note that its not in the main timeline to avoid confusion.
Team Thor contradicts Thor Ragnarok events.
