### ISSUE TITLE
Guardians of the Galaxy vol 2

### ISSUE THREAD

**Issue by ciaron88** [dispossible/MCU-Timeline#4]
Guardians of the Galaxy vol 2 takes place in 2014 right after Guardians of the Galaxy

News sites with the official timeline released by Marvel Studios
https://screenrant.com/mcu-timeline-official/
https://www.technobuffalo.com/marvel-cinematic-universe-timeline

**Comment by dispossible** [comment]
Hi @ciaron88,

Thanks for the message, and sorry it has taken a couple of days to get back to you.

You are quite right, GotG 2 does officially take place in 2014 a few months after the first GotG film. I have just pushed a change to the Chronological Order to amend that into it's correct position.

I have decided to leave it where it is in the Watch Order as I think it feels a little better when watching through the whole list, not to get both of the GotG films in a single block. There are no pressing plot points that need to be resolved from one to the other, and they have no interaction with the rest of the MCU plotting around either of their release dates.

Thanks,
Timothy
