### ISSUE TITLE
Secret Invasion is missing

### ISSUE THREAD

**Issue by valdiclit** [dispossible/MCU-Timeline#47]
Hello, I noticed that Secret Invasion hasn’t been added to the mcu timeline website. Thought I’d remind you if you forgot or didn’t notice. Thank you for your great work I use this website often it’s very practical. Have a nice day

**Comment by dispossible** [comment]
Hey, I have added it in since you asked 🙂, I tend not to jump on the Disney+ shows too quickly as they don't release the episode names ahead of time.
