### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by rickdenhaan** [dispossible/MCU-Timeline#49]
Hi Timothy,

The timeline is missing some information:

* Episode titles for Secret Invasion
* Loki season 2
* What If… season 2
* Echo season 1

I’ll try to get a pull request your way this week, unless you’ve already added them yourself by the time I get around to it 🙂

**Comment by dispossible** [comment]
Hey, thanks for the nudge, been getting behind on the maintenence of this.

I've just pushed a commit with the missing shows, plus Groot season 2 which was also missing.
